/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Block,  BlockType,  CollectionItem,  EmbeddedContent,  EmbeddedContentType,  ListItem,  PreferredView,  Question,  QuestionConstraints,  QuestionOption,  QuestionType,  RenderDoc } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface Block {
      id?: string | null
      type?: types.BlockType | null
      title?: string | null
      preferredView?: types.PreferredView | null
      ordered?: boolean | null
      markdown?: string | null
      items: ListItem[]
      questions: Question[]
      collectionItems: CollectionItem[]
    }
    export interface CollectionItem {
      id?: string | null
      navLabel?: string | null
      title?: string | null
      summary?: string | null
      content?: EmbeddedContent | null
    }
    export interface EmbeddedContent {
      type?: types.EmbeddedContentType | null
      markdown?: string | null
      ordered?: boolean | null
      items: ListItem[]
      questions: Question[]
    }
    export interface ListItem {
      id?: string | null
      navLabel?: string | null
      title?: string | null
      summary?: string | null
      bodyMarkdown?: string | null
    }
    export interface Question {
      id?: string | null
      type?: types.QuestionType | null
      question?: string | null
      context?: string | null
      options: QuestionOption[]
      allowOther?: boolean | null
      otherLabel?: string | null
      answerInstructions?: string | null
      constraints?: QuestionConstraints | null
    }
    export interface QuestionConstraints {
      minSelections?: number | null
      maxSelections?: number | null
      minSentences?: number | null
      maxSentences?: number | null
    }
    export interface QuestionOption {
      id?: string | null
      label?: string | null
      value?: string | null
      description?: string | null
    }
    export interface RenderDoc {
      title?: string | null
      introMarkdown?: string | null
      blocks: Block[]
    }
}