/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum BlockType {
  MARKDOWN = "MARKDOWN",
  LIST = "LIST",
  QUESTIONNAIRE = "QUESTIONNAIRE",
  COLLECTION = "COLLECTION",
}

export enum EmbeddedContentType {
  MARKDOWN = "MARKDOWN",
  LIST = "LIST",
  QUESTIONNAIRE = "QUESTIONNAIRE",
}

export enum PreferredView {
  AUTO = "AUTO",
  STACK = "STACK",
  TABS = "TABS",
}

export enum QuestionType {
  TEXT = "TEXT",
  SINGLE_CHOICE = "SINGLE_CHOICE",
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  RANKING = "RANKING",
}

export interface Block {
  id?: string | null
  type: BlockType
  title?: string | null
  preferredView?: PreferredView | null
  ordered?: boolean | null
  markdown?: string | null
  items: ListItem[]
  questions: Question[]
  collectionItems: CollectionItem[]
  
}

export interface CollectionItem {
  id?: string | null
  navLabel?: string | null
  title?: string | null
  summary?: string | null
  content: EmbeddedContent
  
}

export interface EmbeddedContent {
  type: EmbeddedContentType
  markdown?: string | null
  ordered?: boolean | null
  items: ListItem[]
  questions: Question[]
  
}

export interface ListItem {
  id?: string | null
  navLabel?: string | null
  title?: string | null
  summary?: string | null
  bodyMarkdown: string
  
}

export interface Question {
  id?: string | null
  type: QuestionType
  question: string
  context?: string | null
  options: QuestionOption[]
  allowOther: boolean
  otherLabel?: string | null
  answerInstructions?: string | null
  constraints?: QuestionConstraints | null
  
}

export interface QuestionConstraints {
  minSelections?: number | null
  maxSelections?: number | null
  minSentences?: number | null
  maxSentences?: number | null
  
}

export interface QuestionOption {
  id?: string | null
  label: string
  value?: string | null
  description?: string | null
  
}

export interface RenderDoc {
  title?: string | null
  introMarkdown?: string | null
  blocks: Block[]
  
}
