/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    Block: ClassViewer<'Block', "id" | "type" | "title" | "preferredView" | "ordered" | "markdown" | "items" | "questions" | "collectionItems">;
    
    CollectionItem: ClassViewer<'CollectionItem', "id" | "navLabel" | "title" | "summary" | "content">;
    
    EmbeddedContent: ClassViewer<'EmbeddedContent', "type" | "markdown" | "ordered" | "items" | "questions">;
    
    ListItem: ClassViewer<'ListItem', "id" | "navLabel" | "title" | "summary" | "bodyMarkdown">;
    
    Question: ClassViewer<'Question', "id" | "type" | "question" | "context" | "options" | "allowOther" | "otherLabel" | "answerInstructions" | "constraints">;
    
    QuestionConstraints: ClassViewer<'QuestionConstraints', "minSelections" | "maxSelections" | "minSentences" | "maxSentences">;
    
    QuestionOption: ClassViewer<'QuestionOption', "id" | "label" | "value" | "description">;
    
    RenderDoc: ClassViewer<'RenderDoc', "title" | "introMarkdown" | "blocks">;
    
    
    BlockType: EnumViewer<'BlockType', "MARKDOWN" | "LIST" | "QUESTIONNAIRE" | "COLLECTION">;
    
    EmbeddedContentType: EnumViewer<'EmbeddedContentType', "MARKDOWN" | "LIST" | "QUESTIONNAIRE">;
    
    PreferredView: EnumViewer<'PreferredView', "AUTO" | "STACK" | "TABS">;
    
    QuestionType: EnumViewer<'QuestionType', "TEXT" | "SINGLE_CHOICE" | "MULTIPLE_CHOICE" | "RANKING">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "Block","CollectionItem","EmbeddedContent","ListItem","Question","QuestionConstraints","QuestionOption","RenderDoc",
          ]),
          enums: new Set([
            "BlockType","EmbeddedContentType","PreferredView","QuestionType",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.Block = this.tb.classViewer("Block", [
          "id","type","title","preferredView","ordered","markdown","items","questions","collectionItems",
        ]);
        
        this.CollectionItem = this.tb.classViewer("CollectionItem", [
          "id","navLabel","title","summary","content",
        ]);
        
        this.EmbeddedContent = this.tb.classViewer("EmbeddedContent", [
          "type","markdown","ordered","items","questions",
        ]);
        
        this.ListItem = this.tb.classViewer("ListItem", [
          "id","navLabel","title","summary","bodyMarkdown",
        ]);
        
        this.Question = this.tb.classViewer("Question", [
          "id","type","question","context","options","allowOther","otherLabel","answerInstructions","constraints",
        ]);
        
        this.QuestionConstraints = this.tb.classViewer("QuestionConstraints", [
          "minSelections","maxSelections","minSentences","maxSentences",
        ]);
        
        this.QuestionOption = this.tb.classViewer("QuestionOption", [
          "id","label","value","description",
        ]);
        
        this.RenderDoc = this.tb.classViewer("RenderDoc", [
          "title","introMarkdown","blocks",
        ]);
        
        
        this.BlockType = this.tb.enumViewer("BlockType", [
          "MARKDOWN","LIST","QUESTIONNAIRE","COLLECTION",
        ]);
        
        this.EmbeddedContentType = this.tb.enumViewer("EmbeddedContentType", [
          "MARKDOWN","LIST","QUESTIONNAIRE",
        ]);
        
        this.PreferredView = this.tb.enumViewer("PreferredView", [
          "AUTO","STACK","TABS",
        ]);
        
        this.QuestionType = this.tb.enumViewer("QuestionType", [
          "TEXT","SINGLE_CHOICE","MULTIPLE_CHOICE","RANKING",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}